kind: Deployment
metadata:
name: myapp-deployment
spec:
replicas: 2
selector:
matchLabels:
app: myimage
template:
metadata:
labels:
app: myimage
spec:
containers:
- name: myimage
image: hidpdeveastusbotacr.azurecr.io/hello:76
ports:
- containerPort: 8090
imagePullPolicy: Always
imagePullSecrets:
- name: hidpdeveastusbotacr
